# version: "3.8"
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     depends_on:
#       - mysql
#     environment:
#       DB_HOST: mysql
#       DB_USER: root
#       DB_PASSWORD: admin1234A!
#       DB_NAME: school_management
#       DB_PORT: 3306
#     networks:
#       - app-network
#     volumes:
#       - .:/app
#       - /app/node_modules
#   mysql:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: admin1234A!
#       MYSQL_DATABASE: school_management
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql
#     networks:
#       - app-network
# networks:
#   app-network:
#     driver: bridge
# volumes:
#   mysql-data:

###################Using AWS RDS for database, so no need to run mysql container

version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: schoolmanagement.cjw02mq4ayr4.eu-north-1.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: admin1234A!
      DB_NAME: school_management
      DB_PORT: 3306
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
networks:
  app-network:
    driver: bridge
volumes:
  mysql-data:
